name: Build Plugin

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore src/Community.PowerToys.Run.Plugin.Claude/Community.PowerToys.Run.Plugin.Claude.csproj

      - name: Build
        run: dotnet build src/Community.PowerToys.Run.Plugin.Claude/Community.PowerToys.Run.Plugin.Claude.csproj --configuration Release --no-restore

      - name: Package
        run: |
          Compress-Archive -Path src/Community.PowerToys.Run.Plugin.Claude/bin/Release/* -DestinationPath Community.PowerToys.Run.Plugin.Claude.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Claude-Plugin
          path: Community.PowerToys.Run.Plugin.Claude.zip
