name: Build

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout PowerToys repository
        uses: actions/checkout@v3
        with:
          repository: microsoft/PowerToys
          submodules: recursive
          fetch-depth: 0
          path: PowerToys

      - name: Checkout latest tag
        id: get-latest-tag
        shell: pwsh
        working-directory: PowerToys
        run: |
          git fetch --tags
          $latestTag = (git describe --tags --abbrev=0).ToLower()
          git checkout $latestTag
          git submodule update --init --recursive
          echo "LATEST_TAG=$latestTag" >> $env:GITHUB_OUTPUT
          echo "Latest tag: $latestTag"

      - name: Checkout local repository
        uses: actions/checkout@v3
        with:
          path: ChatClaudePowerToys

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        working-directory: PowerToys
        run: |
          nuget restore PowerToys.sln

      - name: Build solution
        working-directory: PowerToys
        run: |
          msbuild src\common\version\version.vcxproj /p:Configuration=Release /p:Platform=x64 /restore

      - name: Copy ChatClaude Plugin to PowerToys
        run: |
          xcopy /E /I /Y ChatClaudePowerToys\src\Community.PowerToys.Run.Plugin.ChatClaude PowerToys\src\modules\launcher\Plugins\Community.PowerToys.Run.Plugin.ChatClaude

      - name: Build x64
        working-directory: PowerToys
        run: |
          msbuild src\modules\launcher\Plugins\Community.PowerToys.Run.Plugin.ChatClaude\Community.PowerToys.Run.Plugin.ChatClaude.csproj /p:Configuration=Release /p:Platform=x64 /restore

      - name: Build ARM64
        working-directory: PowerToys
        run: |
          msbuild src\modules\launcher\Plugins\Community.PowerToys.Run.Plugin.ChatClaude\Community.PowerToys.Run.Plugin.ChatClaude.csproj /p:Configuration=Release /p:Platform=ARM64 /restore

      - name: Package x64
        run: |
          Compress-Archive -Path PowerToys\x64\Release\RunPlugins\ChatClaude -DestinationPath Community.PowerToys.Run.Plugin.ChatClaude.x64.zip

      - name: Package ARM64
        run: |
          Compress-Archive -Path PowerToys\ARM64\Release\RunPlugins\ChatClaude -DestinationPath Community.PowerToys.Run.Plugin.ChatClaude.ARM64.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Community.PowerToys.Run.Plugin.ChatClaude.x64.zip
            Community.PowerToys.Run.Plugin.ChatClaude.ARM64.zip
          name: Release ${{ steps.get-latest-tag.outputs.LATEST_TAG }}
          tag_name: ${{ steps.get-latest-tag.outputs.LATEST_TAG }}
          make_latest: true
